# export GOPATH=~/go

path=(
  ~/.bin
  ~/.sh
  ~/.local/bin
  ~/.cargo/bin
#   ~/.guard/bin
  ~/.tfenv/bin
  /usr/local/go/bin
#   ${GOPATH}/bin
  $path
)

fpath=(
  ~/.zsh/functions
  $fpath
)

export EDITOR='nvim'

export FZF_DEFAULT_OPTS='--height 40% --reverse --border'

export PIPENV_VENV_IN_PROJECT=1
